### ISSUE TITLE
Expose Lenis instance using `useScrollbar` hook

### ISSUE THREAD

**Issue by baptistebriel** [14islands/r3f-scroll-rig#21]
Hi!

Currently, the [useScrollbar](https://github.com/14islands/r3f-scroll-rig/blob/master/docs/api.md#usescrollbar) hook exposes the `scrollTo` method, but it is impossible to access other methods or the direct instance of Lenis. For example, I'd like to access `start` and `stop` methods. I'm able to access them by [using a ref on the `SmoothScrollbar` component](https://github.com/14islands/r3f-scroll-rig/blob/3c01be368b224c721fad29d21d85e55b9ca09157/src/scrollbar/SmoothScrollbar.tsx#L33-L43), but ideally it would also be possible to access through a hook?

Maybe something similar to this:

```js
const { lenis } = useScrollbar()
```

Let me know if that's possible? Thanks a lot for this library!

**Comment by ffdead** [comment]
Ideally I think we'd want to provide that functionality via the `SmoothScrollbar` or `useScrollbar` hook, which we do via the `locked` property for instance.

But I don't see any reason why we couldn't expose the `lenis` instance too as an escape hatch - we already do it via the the scrollbar ref as you say 👍

**Comment by ffdead** [comment]
@baptistebriel please try `v8.11.11`

`const { __lenis } = useScrollbar()`
