### ISSUE TITLE
"Error [TypeError]: e is not a function" with Next.js 

### ISSUE THREAD

**Issue by palespectre** [14islands/r3f-scroll-rig#22]
Hi !
Could you provide a working example with Next.js ? I can't seem to make it work.
I always get the error "e is not a function" when I wrap my frontpage in `<SmoothScrollbar>`, and I have no idea why.

`- error Error [TypeError]: e is not a function
    at file://node_modules/@14islands/r3f-scroll-rig/dist/scrollrig.modern.js:1:20176`

Thank you

**Comment by ffdead** [comment]
Hi @palespectre that's weird, we use Next.js with the scroll-rig on all our recent projects 🤔

Are you using the `pages` folder or the `app` folder?

**Comment by palespectre** [comment]
Hi @ffdead, nevermind, after deleting the `node_modules` and the `.next` folders, everything started to work... Thank you though for your quick response :)
