### ISSUE TITLE
ScrollScene tracking CSS animation

### ISSUE THREAD

**Issue by fromwhite** [14islands/r3f-scroll-rig#27]
This issue is not a bug, it's a discussion of ideas.

Is it possible to make the scene track CSS animations?
Just like Drei's View, it can track CSS
Views use gl.scissor to cut the viewport into segments You tie a view to a tracking div which then controls the position and bounds of the viewport This allows you to have multiple views with a single, performing canvas These views will follow their tracking elements, scroll along, resize, etc

There are also more possibilities for integrating r3f and CSS animations.

**Comment by ffdead** [comment]
However, if all you do is use `View` you don't actually need the scroll-rig.

The main purpose of the scroll-rig is to avoid calling `getBoundingClientRect()` on each frame and also make it easier to combine the global scene with viewports.

**Comment by fromwhite** [comment]
Thank you for your reply.

Your demo is feasible.

yes indeed, this is different from Drei view component. This idea can be directly implemented using view.
