### ISSUE TITLE
Sticky Scene not reflowing if tracked element goes significantly out of view

### ISSUE THREAD

**Issue by iivvaannxx** [14islands/r3f-scroll-rig#38]
## Preview
I think a video here will do more than a lot of words. Take a look:

https://github.com/14islands/r3f-scroll-rig/assets/47715589/9ca48784-c875-4cad-8c35-c65022a3e65f

## Explanation
First of all, let me tell you that I am using Astro, probably it's not what is expected for this library, but as Astro supports React it just works if you connect everything as it should be in a normal React application.

The problem is simple, I want to have a little interactive Island that displays a 3D model, this island sticks on scroll. The video shows that, as I scroll, it sticks just fine and it rotates with the scroll progress. The issue comes when the element goes out of view.

The first time I scroll the element until it's no longer visible, I just hide a bit over the top edge (I don't scroll much more). If I then go back up it works perfectly, as it should. However, as soon as I scroll for the second time, once the element goes out of view, I scroll until the end of the page. When I try to scroll up again, you can see that the element remains on the bottom of the sticky container and it doesn't go up like before. I am not sure why this happens so I thought of opening an issue.

I think that, for some reason, the "reflow" is not triggering, because if I resize the window (which actually triggers an automatic reflow), then the element gets repositioned and goes back to normal.

### Reproduction

I've built a minimal reproduction from where the video was taken: https://codesandbox.io/p/devbox/r3f-scrollrig-bug-gj29np?file=%2Fsrc%2Fpages%2Fsection.astro%3A106%2C1

I am using Brave as a browser and I am on Linux.

**Comment by iivvaannxx** [comment]
After a bit of debugging, I've found the problem, at least I think it is. Once I figured out why it wasn't working, I gave ChatGPT the full code inside [powerups/StickyScrollScene.tsx](https://github.com/14islands/r3f-scroll-rig/blob/747be0cb387b2ef8c93c8527b58dd7aa0ae876aa/powerups/StickyScrollScene.tsx) and told him what the problem was. The solution it gave me is simple but kind of ugly and I don't know if it's correct, I'll leave that to your judgment. After patching the code everything works as expected.

The problem is that with this component: 
```tsx
const renderAsSticky = (
  el: any,
  children: any,
  size: any,
  childStyle: any,
  scaleMultiplier: number,
  { stickyLerp, fillViewport }: any
) => {
  return ({ scale, ...props }: any) => {
    let childScale = vecn.vec3(parseFloat(childStyle.width), parseFloat(childStyle.height), 1)
    let childTop = parseFloat(childStyle.top)
    let childBottom = size.height - childTop - childScale[1]

    if (fillViewport) {
      childScale = vecn.vec3(size.width, size.height, 1)
      childTop = 0
      childBottom = 0
    }

    // This is wrong
    const offsetTop = el.current.offsetTop

    return (
      // @ts-ignore
      <StickyChild
        offsetTop={offsetTop}
        parentScale={scale}
        childScale={childScale.times(scaleMultiplier)}
        stickyLerp={stickyLerp}
        childTop={childTop}
        childBottom={childBottom}
        scaleMultiplier={scaleMultiplier}
        {...props}
      >
        {children({
          scale: childScale.times(scaleMultiplier),
          parentScale: scale,
          ...props,
        })}
      </StickyChild>
    )
  }
}
```
Once you go out of the viewport, and then back in, it re-renders, thus assigning a new value to `offsetTop`. The original value and the new value after the re-render are not the same. Don't get me wrong, this makes a lot of sense because as you scroll, the sticky container (not the element with `position: sticky`, the container with `position: relative`) `offsetTop` grows (because it sticks). But if you then scroll back up this "new" value makes the `enter`, `sticky`, and `exit` calculations from the `StickyChild` component return different values, thus assigning a wrong `y` value to the object.

The solution? Well within the first renders of this component everything works, the problem only comes when the component re-renders and it assigns a new value to it. The re-rendering happens when the element goes out of the viewport by a significant amount. So, if everything works when `offsetTop` has the original value, and not when it has the "scrolled" value, let's ensure it always has the same initial value, which is the `offsetTop` as if the element was not even scrolled.

```tsx
// This is the "ugly" solution it gave me
const offsetTop = useRef(el.current.offsetTop).current;
```
After this, all the calculations work again, and the sticky positioning works as it should.

**Comment by iivvaannxx** [comment]
This doesn't seem to happen with the official example of `StickyScrollScene`, so I am assuming it has to be because I am using Astro instead of pure React? I don't know. In any case, to solve this I am going to patch the library and move on, if you believe it's just a very specific case that does not happen "normally" (outside of Astro), feel free to close this issue.

**Comment by ffdead** [comment]
Thanks for the report @iivvaannxx !

I think your solution makes a lot of sense - feel free to submit a PR!

I wonder why it always worked so far, maybe React is optimized to not rerender this component but Astro does 🤔

**Comment by mohAmineBrs** [comment]
I had the same issue in Nextjs app and @iivvaannxx workaround did the trick for me too, thanks!
