### ISSUE TITLE
Convert tutorial's Lens into a viewport filter

### ISSUE THREAD

**Issue by teneburu** [14islands/r3f-scroll-rig#39]
Hello, I'm in dire need of help.

I'm trying to copy codrops tutorial to familiarize myself with r3f scroll rig. I'm not used to using r3f.  Using Next 14 app router.
I hope someone can help me understand better what's happening here. 
I've been trying to wrap my head around the use of globalChildren with the useCanvas hook. 
I've tried copying everything happening with Lens. 
The expected result should be a filter covering the whole viewport, instead of a lens centered around the pointer. 
I'm trying to apply post-processing to a plane texture like the Lens. I tried reusing the Text component as an exemple to render the filter on top of it.

Here's my GlobalCanvas with globalChildren inside, with my permanent Filter component wrapped around it : 
```tsx
<GlobalCanvas>
    {(globalChildren) => (
        <>
          <Suspense fallback={null}>
            <Filter>
              {globalChildren}
            </Filter>
          </Suspense>
        </>
    )}
</GlobalCanvas>
<SmoothScrollbar config={{syncTouch: true}} />
```
      
If I use wobble on the text I can see that the WebGLText is rendered. The problem comes from the filter. Expected result would be a pixelated text. [Here's my project's repo](https://github.com/teneburu/10three)

Would be my pleasure to offer coffee. Sorry for taking your time. If anyone at 14islands or anyone familiar with r3f-scroll-rig can explain what I'm doing wrong, I'd be really really grateful.

**Comment by ffdead** [comment]
Hi @teneburu - did you figure this out? Seems the repo has changed so I'll close this issue unless you provide more details 🙏

**Comment by teneburu** [comment]
@ffdead hi, go ahead, i started using something else, i'll take a look at the changes
