### ISSUE TITLE
Module not found: Can't resolve 'lenis'

### ISSUE THREAD

**Issue by AlbertoRocaM** [14islands/r3f-scroll-rig#41]
'@studio-freight/lenis' has been renamed to just 'lenis',

Import trace for requested module:
./src/app/[locale]/client-layout.tsx
 ⨯ ./node_modules/@14islands/r3f-scroll-rig/dist/scrollrig.modern.js:1:847
Module not found: Can't resolve 'lenis'

**Comment by ffdead** [comment]
#43

**Comment by ffdead** [comment]
Published `v8.14.0` with updated dependency
