### ISSUE TITLE
Sticky Scroll Scene incorrect behavior when reloading the page in the middle of parent element.

### ISSUE THREAD

**Issue by dszhusb** [14islands/r3f-scroll-rig#44]
When reloading the page in the middle of the parent element,  the StickyChild component is stuck below the height the page is reloaded at.

**Behavior seen below:**

https://github.com/user-attachments/assets/b7d32db0-71c6-46dc-983d-20367ccaa8b8

**Comment by ffdead** [comment]
@dszhusb did you manage to work around it or have a link to share?

The StickyScrollScene is not a core feature so it's not as well tested as the rest 😇

**Comment by ffdead** [comment]
Potential fix here, would be great if you can test it @dszhusb : https://github.com/14islands/r3f-scroll-rig/pull/48#issuecomment-2489308392

**Comment by ffdead** [comment]
`v8.15.0` published with updated StickyScrollScene
