### ISSUE TITLE
Export useWindowSize hook

### ISSUE THREAD

**Issue by rodleviton** [14islands/r3f-scroll-rig#47]
Hi, thank you for the great library! It would be really helpful if you could export src/hooks/useWindowSize.ts, as it seems like a useful utility. Specifically, I’m looking for a performant way to get the current window dimensions outside of a scroll context. Is there a particular reason why this hasn’t been exported along with the other utilities?

Cheers

**Comment by ffdead** [comment]
Hi @rodleviton - sure we could expose it! 

I believe we never had to use it since usually we get the viewport size from `useThree` or framer-motion when we work on projects :)

**Comment by ffdead** [comment]
`v8.15.0` published with new export
